### ISSUE TITLE
Implement methods in org.jooq.lambda.Seq

### ISSUE THREAD

**Issue by VenkataRaju** [winterbe/streamjs#23]
Seq extends Stream and adds some more useful methods.
You may be interested in adding those.
See here: https://github.com/jOOQ/jOOL

**Comment by winterbe** [comment]
Thanks for your input. I'll look into it. Do you have any specific requirement?

**Comment by VenkataRaju** [comment]
Nope. I'm currently not doing any web development. This is just a suggestion :)

**Comment by winterbe** [comment]
A few methods are now available in Stream.js, like `slice` as well as `takeWhile` and `dropWhile` which seem to equivalent to `limitWhile` and `skipWhile` in jOOL.
