### ISSUE TITLE
TypeError: Illegal invocation

### ISSUE THREAD

**Issue by winterbe** [winterbe/streamjs#33]
This code fails:

```js
Stream.of(1, 2, 3)
        .forEach(console.log);
```

Error:

```
TypeError: Illegal invocation
    at Pipeline.terminal.forEach (http://localhost:63342/streamjs/stream.js:561:20)
    at Pipeline.<anonymous> (http://localhost:63342/streamjs/stream.js:920:39)
    at Object.<anonymous> (http://localhost:63342/streamjs/test/test-introduction-compiled.js:28:24)
```

**Comment by winterbe** [comment]
Currently you have to write this:

```js
Stream.of(1, 2, 3)
    .forEach(function(n) {
        console.log(n);
    );
```

**Comment by winterbe** [comment]
Reason for the error is that you cannot call `console.log` with a custom object bound to `this`. This fails in Chrome:

```js
console.log.call({}, "hi there");
```

**Comment by erosb** [comment]
Hi!
I don't think this is a streamjs bug. This is how javascript works.
A workaround is to wrap the call in an anonymous function (as you wrote above) or using the `bind` function like this: `Stream.of(1, 2, 3).forEach(console.log.bind(console));

**Comment by winterbe** [comment]
I agree with you that it's not directly a bug in Stream.js but writing `.forEach(console.log)` for quickly debugging stuff is quite handy from time to time so I want Stream.js to handle this properly.

I've come up with a solution for `forEach` and `peek` although it's not nice to explicitly check this special case but I think it's worth it.

**Comment by erosb** [comment]
In such case I think you can add some new methods:

 * `Stream.logEach()` : logs all entried to console.log properly
 * `Stream.logEach(logger)` : receives the name of a logger function in console (can be "log", "info", "error", "debug")

These can be terminal operations. Maybe you could add 2 nonterminal operations too, but I don't think that would make sense (and I don't have any idea about a proper naming for them).

**Comment by winterbe** [comment]
Thanks. It's fixed.
