### ISSUE TITLE
Static factory method for creating streams from arrays

### ISSUE THREAD

**Issue by erosb** [winterbe/streamjs#34]
I'm working on a [typescript definition file](https://github.com/erosb/DefinitelyTyped/blob/streamjs/streamjs/streamjs.d.ts) for streamjs.

I found that the only way to create a stream from an array is to invoke `Stream(array)` as a function. It works in javascript but sadly typescript currently does not have support to define a class and a function with the same name, so I cannot include it in my typescript definition file.

I would be pleased if you could add a `Stream.from(array)` static factory method so that I could create an appropriate definition for it in my streamjs.d.ts file.

**Comment by winterbe** [comment]
I've added `Stream.from` as an alias to the `Stream` constructor function. The change will be part of the next release, which will be probably Version 1.4.1 in the next days.

Please let me know when your work is successful so I can give it a try. :+1:

**Comment by erosb** [comment]
Hi!
I've just [pushed some changes](https://github.com/erosb/DefinitelyTyped/commit/bd123fb8824cc1a554ed1fa4abc2f4331ceaff17) to my streamjs.d.ts file.
I will wait for your next release before sending a pull request to borisyankov/DefinitelyTyped so I can also add definition for the `from(array)` method. I recommend making it 1.5.0 since it is a backward-compatible API change (afair according so semver the minor version number should be incremented).

Sadly the rest of the unsupported methods cannot be defined in my .d.ts file, since currently the typescript compiler fails to infer the actual generic types when it is represented only by the return type and not by one of the parameter types. This is the case for `Stream.empty()`, `Optional.empty()`, `Stream.map(path)` and `Stream.flatMap(path)` . But it is a typescript issue, not much to do with it in streamjs

**Comment by winterbe** [comment]
You're right, I have to bump version to 1.5.0. I want to fix #33 before publishing this version.

If there's anything I could do to help with those missing typescript methods mentioned above, just let me know.

**Comment by winterbe** [comment]
@erosb I've published Version 1.5.0.

**Comment by erosb** [comment]
Thank you :) I've just updated my streamjs.d.ts file and sent a pull request to borisyankov/DefinitelyTyped ( https://github.com/borisyankov/DefinitelyTyped/pull/4646 )

**Comment by winterbe** [comment]
@erosb It seems the Travis CI build is failing for your pull request.

**Comment by erosb** [comment]
ehh damn.. thanks, I didn't get any notification about it.
I fixed the build problem, now it is fine (hopefully)

**Comment by winterbe** [comment]
Your PR has been merged. Again thanks for your effort. I've put a link to the README [here](https://github.com/winterbe/streamjs#api-documentation). :clap:
