### ISSUE TITLE
Avoid pre-loading the range to an array

### ISSUE THREAD

**Issue by erosb** [winterbe/streamjs#35]
I found that the `Stream.range()` constructor loads all elements of the range into an array, then initializes a new stream for the resulting array. It would be less memory consuming to initialize the seed with an iterator with `seed=startInclusive` and an incrementer function. The upper bound of the range can be expressed with `limit()`.

**Comment by winterbe** [comment]
This makes so much sense. Thanks for your contribution! All tests are passing so I'll merge your PR into master.
