### ISSUE TITLE
Algorithm for sleep (a/k/a pause, wait, delay)

### ISSUE THREAD

**Issue by dschalk** [winterbe/streamjs#48]
It would be nice to have a function to stop the propagation of chained computations for an arbitrary number of milliseconds. I don't see one in the API. Do you have an undocumented function you could share, or a suggestion on how to go about coding one.

I have been chaining monadic creations (https://github.com/dschalk/reactive-monads, explained at https://github.com/dschalk/mobservable-monads. With setTimeout, chain propagation continues while setTimeout does its thing, resulting in failure. Bringing the whole browser tab to a screeching halt with "while" algorithms isn't cool. I'm using React.js with webpack, so I have easy access to ES6 promises and they do work (see https://github.com/dschalk/mobservable-monads) but the two-step procedure is unsatisfying. 

Suggestion: you might want to consider incorporating a function like JQuery's "delay()" in streamjs.

**Comment by winterbe** [comment]
Thanks for your feedback. In the current state Stream.js is completely synchronous. Asynchronous operations via `setTimeout` is not supported out of the box.

What you can do today with Stream.js is to create an iterator by calling `iterator()` at the end of the stream. This returns immediately  without processing any operation. You can then use this iterator to process the stream asynchronously by yourself.

I could imagine to add convenient methods to support asynchronous processing in the future, e.g. vja terminal operation: `iterateAsync(fn, delay)`

> However some stateful operations like `sorted` will still be performed synchronously on the whole input collection.
