### ISSUE TITLE
QUnit tests -initialization failure

### ISSUE THREAD

**Issue by erosb** [winterbe/streamjs#49]
After updating to the head revision (commit 205ee78cbd94bd8aed69fab67a8c7b0d9c7f0c3f ) I ran the `npm install ` command, then `grunt test` , I got the following output:

```
Running "eslint:target" (eslint) task


Running "qunit:files" (qunit) task
Testing test/index.html 
>> PhantomJS timed out, possibly due to a missing QUnit start() call.
Warning: 1/1 assertions failed (0ms) Use --force to continue.

Aborted due to warnings.
```

Then I opened the `test/index.html` in Chrome and I got this error in the console: `GET file:///..../streamjs/node_modules/babel-core/browser-polyfill.js net::ERR_FILE_NOT_FOUND` Well the browser is true, that file does not exist (although the `node_modules/babel-core/` directory is present).

What am I doing wrong?

**Comment by winterbe** [comment]
I guess it's due to Babel 5 -> version 6. I ran into similar problems at work recently. Babel renamed the polyfill file. Have to either switch to latest Babel version or remove ^ from package.json.

**Comment by winterbe** [comment]
Problem is fixed with latest commit 5797efa688c4dcc99889b4a05a2e3f413ad1e11a. I've migrated the project to latest Babel version.

**Comment by erosb** [comment]
Tests passing, cool, thank you!

**Comment by winterbe** [comment]
You're welcome. Thanks for pointing that out.
