### ISSUE TITLE
Can you not use this with actual streams?

### ISSUE THREAD

**Issue by brandonros** [winterbe/streamjs#56]
I don't see any examples on how to use this in a .pipe context

```
request.get({url: 'https://some.json/endpoint'})
.pipe(Stream.transformStuffHere)
```

Any advice? Kind of misleading... I could get pairing it with JSONStream, but still couldn't think of how to handle it.

**Comment by winterbe** [comment]
Streamjs is for synchronously iterable data only. Dunno what pipe context you’re referring to but I guess it’s asynchronous so it won’t work with Streamjs. You should look for libs like RxJS.
