### ISSUE TITLE
Stream cannot be used by esm module

### ISSUE THREAD

**Issue by WORMSS** [winterbe/streamjs#57]
I tried to do
```html
<script type="module">
```
```js
import Stream from 'https://unpkg.com/streamjs' // throws error, no default export
import { Stream } from 'https://unpkg.com/streamjs' // throws error, no Stream export
import { * as Stream } from 'https://unpkg.com/streamjs' // no error, but reports as an empty Module
import 'https://unpkg.com/streamjs' // throw error, root is undefined
```
(this last one proved most enlightening)

I added 
```js
var root = (typeof global === 'object' && global) || (typeof globalThis === 'object' && globalThis) || this,
```
and I was atleast able to get `import 'https://unpkg.com/streamjs'` to work and make Stream global within the module. (Not ideal, but the best I had)

Your contrib.md said to make an issue here for discussion before making a PR.

**Comment by winterbe** [comment]
This project is no longer maintained. Feel free to fork the project.
